### ISSUE TITLE
Issues applying the RIOXX patch

### ISSUE THREAD

**Issue by jonas-atmire** [4Science/rioxxintegration#6]
# Scope of the problem
As part of an upgrade of a client codebase (that previously had the RIOXX 5 patch installed) to a DSpace 6.3, we've been applying the new version of RIOXX.
During this process we've encountered some problems that will need to be addressed in the general patch.

(Please note that we have had some tries at trying to get this fixed in other ways, but have refrained from applying too many changes for the time being, as the actual patch will greatly benefit from being fixed)
### SNAPSHOT versions
* The [installation documentation prerequisites](https://github.com/4Science/rioxxintegration#prerequisites--) mention that a 6.3 needs to be upgraded to the 6.4-SNAPSHOT immediately because of dependencies (Bower/JRuby/SASS mentioned in the docs)
    * Since those build problems are fixable in a separate way, and don't have any bearing on the actual RIOXX patch, this should not be a prerequisite

Long story short -> A 'SNAPSHOT' version should never be used to start a codebase/repository customisation on as they are prone to changes that could lead to problems with patch applications later on. (And only released versions should be taken into account)
### Overwritten config directory
* It seems that the [config directory](https://github.com/4Science/rioxxintegration/tree/master/rioxxintegration-api/src/main/resources/dspace/config) that is present in the RIOXX patch dependency is completely overwriting the config directory of the repository codebase that it's being applied into.
* This has the effect that any configuration change is completely ignored (Ie, a change in xmlui/dspace.cfg/etc)
    * In an unaltered DSpace, this does not become apparent, since the patch has also been 'created' against an unaltered DSpace codebase. 
    * As soon as there is any customisation to the configuration, the application of the patch removes all of that, and a rebuild shows that it's reverted/overwritten previous changes
* The patch enables [XMLWorkflow by default](https://github.com/4Science/rioxxintegration/blob/6.3.0/rioxxintegration-api/src/main/resources/dspace/config/xmlui.xconf#L111)
    * This is not a requirement for the RIOXX patch, so should be removed altogether     
### Issues with regards to Authority
* There is a problem with the authority framework that is used in the RIOXX patch (Either because of import ordering, or because of overwritten classes)
    * When applying this patch to a fairly clean DSpace (No actual codechanges), this cause the authority-indexing to fail because of changed in the AuthorityIndexerInterface -> isConfiguredProperly
    * There are quite a lot of [generated method stubs that simply return ```null``` objects](https://github.com/4Science/rioxxintegration/blob/c894f197d3fc38689b608cf0058a5eff06d92712/rioxxintegration-api/src/main/java/org/dspace/authority/indexer/FunderAuthorityIndexer.java#L52) -> This will cause quite a lot of  NullPointerExceptions to be thrown, once the general authority indexing is fixed.
# Proposed solution:
### SNAPSHOT versions
* The mention of the upgrade to a snapshot (in my opinion), should be removed altogether as these build problems are not relevant for all parties that would apply the patch. (This also has to do with the versions that the user might have installed, and not the codebase itself) 
    * If this is fixable in another way (Which it is), this can be taken up in documentation     
        * Changing the build to use yarn instead of bower fixes this as well (In combination with a minor change in [_dspace_variables.scss](https://github.com/4Science/rioxxintegration/blob/6.3.0/rioxxintegration-xmlui/src/main/webapp/themes/Mirage2/styles/classic_mirage_color_scheme/_dspace_variables.scss#L10)
```scss
$fa-font-path: "../node_modules/font-awesome/fonts";
@import "../../node_modules/font-awesome/scss/font-awesome";
```
### Overwritten config directory
Some things that spring to mind are: 
* This configuration needs to be removed from the dependency completely, and applied through manual means as could be described in the docs
    * When the docs are sufficiently extensive, this becomes just an extra step in the installation that should be fairly straightforward
    * The actual config differences can be present in the .patch files instead of in the maven dependency
 * XMLWorkflow changes need to be reverted
### Issues with regards to Authority
* All possible NullPointers will need to be removed from the authority related code
    * Ie, if calling a method to retrieve values based on certain parameters, it should search, instead of simply returning null
* The patch install shouldn't break any existing code, and shouldn't 'alter' any default DSpace code that isn't strictly required 
    * index-authority should work as is, without any workarounds in the dependencies 
* The docs should also mention some steps to take with regards to tests that can check if authority is correct or not (Ie, run index-authority for example)

**Comment by rfazio** [comment]
Hi @jonas-atmire 

**SNAPSHOT versions**
It was decided to use the SNAPSHOT from version 6.4 (which was declared imminent at the time of the development), in agreement with JISC, because the tag from 6.3 was NOT usable as there were problems on the build. The snapshot is identical to the 6.4 tag. Anyway on github there is also the REF/RIOXX version for tag 6.3, but it must be fixed due to the mentioned problems affecting the build.

**Overwritten config directory**
The patch is fit for standard repositories that are not customized, so local configurations should be ported into the REF/RIOXX addon (the code is available and can be edited). 

**Issues with regards to Authority**
The patch features a simple way to incorporate the use of authority, also depending on implementation choices made on previous versions. Anyway the suggested ideas can be turned into a PullRequest with the fixes, so that we can evaluate/incorporate them. 

Regards
Riccardo

**Comment by jonas-atmire** [comment]
@rfazio 
Thanks for the reply, sorry that I haven't been able to reply earlier.

I'm don't really agree with the responses to the separate problems.

Apart from the 6.3 tag being indeed usable as is, the other problems are completely breaking any codebase the patch would be applied to and don't adhere to how a patch should work.

I get that SOME changes can be required when applying a patch, but that should only be relevant for some minor problems that the patch application might create, not for the ENTIRE config directory. (For example, in the previous RIOXX codebase,  it does mentioned that some files might not be merged automatically, but, from experience, I know that those are small, and that it's only if a certain config has been altered before -> https://github.com/atmire/rioxx#3-apply-the-patch-)

That being said, I'm guessing it would be able to be applied on a default dspace, as it would overwrite the config completely, but the problem is that ANY dspace is configured separately, and that would require a change for every install, for example, it overwrites all config:
* https://github.com/4Science/rioxxintegration/blob/master/rioxxintegration-api/src/main/resources/dspace/config/dspace.cfg#L26
* The unaltered dspace would only be usable on localhost:8080
* It overwrites config it has no business overwriting
* If anyone was to overwrite the config in the patch as you mentioned, that would also have a negative impact on any possible patch changes
    * If fixes are done to the patch that ALSO involve config changes, it would most likely result in weird merge conflicts that could have been avoided altogether  

In addition to that, for the issues regarding the authority, you mention it's `depending on implementation choices made on previous versions`, but even for an unaltered DSpace this is completely unusable because of the points mentioned before.

You also mention that `the suggested ideas can be turned into a PullRequest with the fixes, so that we can evaluate/incorporate them`, but as the base patch isn't completely functional, I don't think the community is to be involved in this as there are enough open issues to fix first in the general DSpace codebase.

**Comment by rfazio** [comment]
Hi @jonas-atmire ,

thanks for your comments. I understand and agree that things can be done in several ways and often one solution is not always the best solution for all the scenarios.
What JISC has requested and what has been implemented is the simpler approach to cover the scenario where the DSpace repository has really no o minor customisations and the institution needs to take the minimal decision and configuration of the RIOXX and REF features together. The goal is to have both the RIOXX and REF patches applied. If an institution has the support of a service provider it can benefit of the service provider experience to have the patch applied in a more tailored way. This is what we offer to our customer and if needed we can provide help on your customer.

Due to this context, the claim against the snapshot release and enabling the xmlworkflow cannot be accepted. JISC has preferred to keep minimal the decision to take for the installation of the feature and as xmlworkflow is supported and provide at least the same features of the legacy workflow it was not an issue to imply it activation as part of this patch. As the xmlwokflow has been introduced by Atmire on previous version I guess that this is not an issue for you. Moreover, version 7 thanks to the improvements made by 4Science has set it as the default and only workflow engine so there are also no issues in regards of future migrations.

About the configuration the recommended approach during a migration is always to start with the default configuration of the new version or the patched version in this case and re-apply the local configuration changes over such default taking the opportunity to revisit such  changes if appropriate. Moreover, moving from version 5 to version 6 you will need to perform major configuration rework due to the changed configuration system and take benefit of the local.cfg file where you can keep isolated the local configuration such as the dspace url that you mention. Nevertheless, **I agree that is inconvenient to have the source configuration files overwritten during the package by the addon without notice so we are going to revisit this approach in the next weeks to avoid it.** The default configuration will be supplied as part of the patch file that currently update the pom.xml files.

With regard to your last sentence:

> You also mention that the suggested ideas can be turned into a PullRequest with the fixes, so that we can evaluate/incorporate them, but as the base patch isn't completely functional, I don't think the community is to be involved in this as there are enough open issues to fix first in the general DSpace codebase.

now that are clarified the reasons behind the high level decisions (snapshot version, xmlworkflow, completely pre-configured by default) can you create more detailed tickets about which are the open issues to get fixed first? a description of the steps to perform to reproduce the issue and the stacktrace of the identified errors would be very useful and will help our developers to work on it.

**Comment by rfazio** [comment]
Hi @jonas-atmire ,

just to update that we have applied the modifications in order to avoid the overwrite of  configuration files;
